// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utyalymudtsngoipycjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0eWFseW11ZHRzbmdvaXB5Y2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyODkwMzMsImV4cCI6MjA3Njg2NTAzM30.RuXaXigdX0-MG9C2T0vh5dpEGSyn7Tcan8323VcYJc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});